<?php

/**
 * BaseBotonesFavoritos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $bf_user_id
 * @property integer $bf_btn_id
 * @property sfGuardUser $sfGuardUser
 * @property Botones $Botones
 * 
 * @method integer          getBfUserId()    Returns the current record's "bf_user_id" value
 * @method integer          getBfBtnId()     Returns the current record's "bf_btn_id" value
 * @method sfGuardUser      getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Botones          getBotones()     Returns the current record's "Botones" value
 * @method BotonesFavoritos setBfUserId()    Sets the current record's "bf_user_id" value
 * @method BotonesFavoritos setBfBtnId()     Sets the current record's "bf_btn_id" value
 * @method BotonesFavoritos setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method BotonesFavoritos setBotones()     Sets the current record's "Botones" value
 * 
 * @package    portal-educacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBotonesFavoritos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('botones_favoritos');
        $this->hasColumn('bf_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('bf_btn_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'bf_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Botones', array(
             'local' => 'bf_btn_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}