<?php

/**
 * BotonesFavoritosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BotonesFavoritosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BotonesFavoritosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BotonesFavoritos');
    }
}