<?php

/**
 * BotonesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BotonesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BotonesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Botones');
    }

    public function getFavoritos($rol_id, $user_id)
    {
    	//trae todos los botones de la cate
    	$query = self::getInstance()->createQuery('b')
    				->innerJoin('b.Categorias c')
    				->innerJoin('c.RolesCategorias rc')
    				->innerJoin('b.Favoritos bf')
    				->andWhere('bf.bf_user_id = ?', $user_id)
    				->andWhere('rc.rol_group_id = ?', $rol_id)
    				->andWhere('b.btn_activo = true');

    	return $query->execute();
    }

    public function getTotalFavoritos($rol_id, $user_id)
    {
    	//trae todos los botones de la cate
    	$query = self::getInstance()->createQuery('b')
    				->innerJoin('b.Categorias c')
    				->innerJoin('c.RolesCategorias rc')
    				->innerJoin('b.Favoritos bf')
    				->andWhere('bf.bf_user_id = ?', $user_id)
    				->andWhere('rc.rol_group_id = ?', $rol_id)
    				->andWhere('b.btn_activo = true')
    				->count();

    	return $query;
    }
}