<?php

/**
 * CategoriasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Categorias');
    }

    public function getNoFavoritos($rol_id)
    {
        //trae todos los botones de la cate
        $query = self::getInstance()->createQuery('c')
                    ->innerJoin('c.RolesCategorias rc')
                    ->innerJoin('c.Botones b')
                    ->leftJoin('b.Favoritos bf')
                    ->andWhere('bf.bf_user_id is null')
                    ->andWhere('rc.rol_group_id = ?', $rol_id)
                    ->andWhere('b.btn_activo = true')
                    ->orderBy('c.cat_posicion asc');

        return $query->execute();
    }
}