<?php

/**
 * NoticiasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NoticiasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NoticiasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Noticias');
    }

    //listo las noticias activas y programadas por fecha
    public function getNoticias(){
    	$query = self::getInstance()->createQuery('n')
    				//->select('COUNT(n.*)')
    				->andWhere('n.not_activo = true')
    				->andWhere('n.not_inicio_pub <= ? and n.not_fin_pub >= ?', array(date('Y-m-d H:i:s'), date('Y-m-d H:i:s')));

    	return $query->execute();
    }

    //obtengo el total de noticias
    public function getTotalNoticias(){
    	$query = self::getInstance()->createQuery('n')
    				->andWhere('n.not_activo = true')
    				->andWhere('n.not_inicio_pub <= ? and n.not_fin_pub >= ?', array(date('Y-m-d H:i:s'), date('Y-m-d H:i:s')))
    				->count();

    	return $query;
    }

}